create table if not exists public.app_activity_log (
  id bigint generated by default as identity not null,
  order_id uuid not null,
  order_item_id uuid null,
  old_quantity numeric null,
  new_quantity numeric null,
  reason text not null,
  created_at timestamp with time zone not null default now(),
  order_details json null,
  activity text not null default ''::text,
  changed_by uuid null,
  changed_at timestamp with time zone null,
  constraint log_table_pkey primary key (id),
  constraint log_table_order_id_fkey foreign KEY (order_id) references orders (id),
  constraint log_table_order_item_id_fkey foreign KEY (order_item_id) references order_items (id)
);

create table if not exists public.categories (
  id uuid not null default gen_random_uuid (),
  outlet_id uuid not null,
  name text not null,
  description text null,
  sort_order integer null default 0,
  is_active boolean null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint categories_pkey primary key (id),
  constraint categories_outlet_id_fkey foreign KEY (outlet_id) references outlets (id) on delete CASCADE
);

create trigger update_categories_updated_at BEFORE
update on categories for EACH row
execute FUNCTION update_updated_at_column ();

-- Failed/successful approval attempts, used to throttle password guessing
-- (5 failures per username per 10 minutes). RLS on with NO policies: only the
-- security-definer verifier reads/writes it. No password is ever stored.
create table if not exists editor_approval_attempts (
  id bigint generated always as identity primary key,
  outlet_id uuid not null,
  username text not null,
  requested_by uuid null,
  succeeded boolean not null,
  attempted_at timestamptz not null default now()
);
create index if not exists idx_editor_approval_attempts_recent
  on editor_approval_attempts (outlet_id, lower(username), attempted_at desc)
  where not succeeded;
alter table editor_approval_attempts enable row level security;

-- ============================================================================
-- INVOICE NUMBERING
-- ============================================================================
-- Format: YYYY-MM-DD-NNNNN (today's date + a 5-digit running count, e.g.
-- "2026-09-28-00042"). Assigned automatically the moment an order is
-- INSERTed (by Android, via the anon key — see assign_invoice_number()
-- below), not at settle/complete time:
--   - dine-in: the table's FIRST order of a new sitting gets a fresh number;
--     every later round on that same table reuses it, until the table is
--     settled + fully paid (same "current batch" predicate used everywhere
--     else — list_tables_for_outlet()/fetchTableBatchOrders() — status <>
--     'cancelled' and not (completed and payment_details is not null)).
--     Once paid, the table frees and the NEXT sitting gets a new number.
--   - takeaway/pickup: every order gets its own fresh number, no reuse.
-- The running count (NNNNN) is per-outlet and does NOT reset daily — it
-- keeps climbing across days until an admin manually resets it from the
-- Settings page (reset_invoice_sequence(), db/functions.sql). Cancelled
-- orders keep whatever number they were assigned — numbers are never
-- reused or renumbered, so gaps from a cancellation are expected, not a
-- bug (standard for audit-safe invoice numbering).
alter table orders
  add column if not exists invoice_number text;

create table if not exists invoice_sequences (
  outlet_id uuid primary key references outlets(id),
  current_seq integer not null default 0,
  last_reset_at timestamptz,
  reset_by uuid references auth.users(id)
);

-- Locked down completely: no anon/authenticated policies at all. The ONLY
-- way to read or write this table is through the security-definer functions
-- below (assign_invoice_number(), db/functions.sql's
-- get_invoice_sequence_status()/reset_invoice_sequence()), which run with
-- elevated privileges and so aren't blocked by RLS having zero policies —
-- direct client access (anon or authenticated) is not needed anywhere and
-- is fully denied.

create table public.menu_items (
  id uuid not null default gen_random_uuid (),
  outlet_id uuid not null,
  category_id uuid not null,
  name text not null,
  description text null,
  search_key character varying null,
  price numeric(10, 2) not null,
  cost_price numeric(10, 2) null,
  image_url text null,
  is_available boolean null default true,
  is_active boolean null default true,
  is_veg boolean not null default true,
  cooking_time integer null default 0,
  sort_order integer null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  container_charge numeric null default '5'::numeric,
  constraint menu_items_pkey primary key (id),
  constraint menu_items_category_id_fkey foreign KEY (category_id) references categories (id) on delete CASCADE,
  constraint menu_items_outlet_id_fkey foreign KEY (outlet_id) references outlets (id) on delete CASCADE
);

create trigger update_menu_items_updated_at BEFORE
update on menu_items for EACH row
execute FUNCTION update_updated_at_column ();

create table public.order_items (
  id uuid not null default gen_random_uuid (),
  order_id uuid not null,
  menu_item_id uuid not null,
  quantity integer not null default 1,
  unit_price numeric(10, 2) not null,
  total_price numeric(10, 2) not null,
  status text null default 'pending'::text,
  notes text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  kot_printed boolean null default false,
  kot_printed_at timestamp with time zone null default now(),
  is_deleted boolean null default false,
  edited_at timestamp with time zone null,
  constraint order_items_pkey primary key (id),
  constraint order_items_menu_item_id_fkey foreign KEY (menu_item_id) references menu_items (id) on delete CASCADE,
  constraint order_items_order_id_fkey foreign KEY (order_id) references orders (id) on delete CASCADE,
  constraint order_items_status_check check (
    (
      status = any (
        array[
          'pending'::text,
          'confirmed'::text,
          'preparing'::text,
          'ready'::text,
          'served'::text
        ]
      )
    )
  )
);

create index IF not exists idx_order_items_order_id on public.order_items using btree (order_id) ;

create index IF not exists idx_order_items_pending on public.order_items using btree (order_id) 
where
  (kot_printed = false);

create index IF not exists idx_order_items_not_deleted on public.order_items using btree (order_id) 
where
  (not is_deleted);

create trigger update_order_items_updated_at BEFORE
update on order_items for EACH row
execute FUNCTION update_updated_at_column ();


create table public.order_sequences (
  id uuid not null default gen_random_uuid (),
  outlet_id uuid not null,
  current_number integer not null,
  starting_number integer not null,
  last_reset timestamp with time zone not null default now(),
  constraint order_sequences_pkey primary key (id),
  constraint order_sequences_outlet_id_key unique (outlet_id),
  constraint order_sequences_outlet_id_fkey foreign KEY (outlet_id) references outlets (id) on delete CASCADE
);

create table public.orders (
  id uuid not null default gen_random_uuid (),
  outlet_id uuid not null,
  table_id uuid null,
  order_number text not null,
  order_type text null default 'dine_in'::text,
  status text null default 'pending'::text,
  subtotal numeric(10, 2) null default 0,
  tax_amount numeric(10, 2) null default 0,
  discount_amount numeric(10, 2) null default 0,
  total_amount numeric(10, 2) null default 0,
  payment_status text null default 'pending'::text,
  payment_method text null,
  notes text null,
  waiter_id uuid null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  token_number integer null,
  container_amount numeric null default '0'::numeric,
  paid_at timestamp with time zone null,
  confirmed_at timestamp with time zone null,
  settled_at timestamp with time zone null,
  payment_details jsonb null,
  invoice_number text null,
  constraint orders_pkey primary key (id),
  constraint orders_outlet_id_order_number_key unique (outlet_id, order_number),
  constraint orders_table_id_fkey foreign KEY (table_id) references tables (id) on delete set null,
  constraint orders_outlet_id_fkey foreign KEY (outlet_id) references outlets (id) on delete CASCADE,
  constraint orders_payment_status_check check (
    (
      payment_status = any (
        array[
          'pending'::text,
          'partial'::text,
          'completed'::text,
          'refunded'::text
        ]
      )
    )
  ),
  constraint orders_order_type_check check (
    (
      order_type = any (
        array[
          'dine_in'::text,
          'takeaway'::text,
          'delivery'::text
        ]
      )
    )
  ),
  constraint orders_status_check check (
    (
      status = any (
        array[
          'pending'::text,
          'confirmed'::text,
          'preparing'::text,
          'ready'::text,
          'served'::text,
          'completed'::text,
          'cancelled'::text
        ]
      )
    )
  )
);

create index IF not exists idx_orders_outlet_created_at on public.orders using btree (outlet_id, created_at desc) ;

create index IF not exists idx_orders_outlet_invoice_number on public.orders using btree (outlet_id, invoice_number) 
where
  (invoice_number is not null);

create index IF not exists idx_orders_outlet_settled on public.orders using btree (outlet_id, status, settled_at) ;

create index IF not exists idx_orders_outlet_completed on public.orders using btree (outlet_id, status, created_at) ;

create trigger trg_assign_invoice_number BEFORE INSERT on orders for EACH row
execute FUNCTION assign_invoice_number ();

create trigger update_orders_updated_at BEFORE
update on orders for EACH row
execute FUNCTION update_updated_at_column ();


create table public.outlets (
  id uuid not null default gen_random_uuid (),
  name text not null,
  address text null,
  phone text null,
  email text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  gst_number text null,
  constraint outlets_pkey primary key (id)
) ;

create trigger update_outlets_updated_at BEFORE
update on outlets for EACH row
execute FUNCTION update_updated_at_column ();


create table public.tables (
  id uuid not null default gen_random_uuid (),
  outlet_id uuid not null,
  table_number text not null,
  capacity integer not null default 4,
  floor_area text null default 'Main'::text,
  status text null default 'available'::text,
  position_x integer null default 0,
  position_y integer null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint tables_pkey primary key (id),
  constraint tables_outlet_id_table_number_key unique (outlet_id, table_number),
  constraint tables_outlet_id_fkey foreign KEY (outlet_id) references outlets (id) on delete CASCADE,
  constraint tables_status_check check (
    (
      status = any (
        array[
          'available'::text,
          'occupied'::text,
          'reserved'::text,
          'cleaning'::text
        ]
      )
    )
  )
) ;

create trigger update_tables_updated_at BEFORE
update on tables for EACH row
execute FUNCTION update_updated_at_column ();


-- GST rate per outlet. The New Order page reads the newest active row for the
-- signed-in user's outlet. Only manager/owner/admin may change it.
create table if not exists tax_settings (
  id           uuid primary key default gen_random_uuid(),
  outlet_id    uuid not null references outlets(id),
  name         text not null default 'GST',
  rate_percent numeric(5,2) not null check (rate_percent >= 0 and rate_percent <= 100),
  is_active    boolean not null default true,
  updated_at   timestamptz not null default now()
);
create index if not exists idx_tax_settings_outlet on tax_settings (outlet_id, is_active, updated_at desc);

alter table tax_settings enable row level security;

drop policy if exists "staff read own outlet tax" on tax_settings;
create policy "staff read own outlet tax" on tax_settings
  for select to authenticated
  using (exists (select 1 from profiles p
                  where p.user_id = auth.uid() and p.outlet_id = tax_settings.outlet_id));

drop policy if exists "managers manage own outlet tax" on tax_settings;
create policy "managers manage own outlet tax" on tax_settings
  for all to authenticated
  using (exists (select 1 from profiles p
                  where p.user_id = auth.uid() and p.outlet_id = tax_settings.outlet_id
                    and p.role in ('manager', 'owner', 'admin')))
  with check (exists (select 1 from profiles p
                  where p.user_id = auth.uid() and p.outlet_id = tax_settings.outlet_id
                    and p.role in ('manager', 'owner', 'admin')));